name: 游불

on:
  push:
    paths:
      - modules/**
      - APP-MANAGER
      # Trigger if action file change !! DEBUG important
      - .github/workflows/to-weblate.yml

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: 游불

jobs:
  sync-files:
    name: 游불
    runs-on: ubuntu-22.04

    steps:

      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gettext
          version: 1.0

      - name: regen
        run: |
          # Files for string extraction
          list="APP-MANAGER modules/database.am modules/install.am modules/management.am modules/sandboxes.am modules/template.am modules/translate.am"
          # Remove old pot
          if [ -f source.pot ]; then
            rm source.pot
          fi
          # extract strings from list
          for file in ${list}; do
            echo "$file"
            # Extract strings for translation
            bash --dump-po-strings "$file" >> source.pot
          done
          cat source.pot > temp.po
          # remove duplicities from po file
          msguniq temp.po -o source.po || cat temp.po >> $GITHUB_STEP_SUMMARY
          # recreate fixed pot file
          msgcat --output-file=source.pot --unique --indent --no-wrap source.po
          rm -f temp.po
          rm -f *.po~

      - name: monorepo
        run: |
          git clone https://github.com/${{ github.repository_owner }}/monorepo
          cd monorepo
          cp ../source.po ../source.pot localization/
          git add localization/source.po
          git add localization/source.pot
          echo '----------------------------------------------------------------------------'

      - name: Push
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          cd monorepo
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m 游불
            git push https://<TOKEN>@github.com/am-community/monorepo && echo "translation source prepared" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          TOKEN: ${{ TOKEN }}
