name: "游불"

on:
  push:
    paths:
      - modules/**
      - APP-MANAGER
      # Trigger if action file change !! DEBUG important
      - .github/workflows/to-weblate.yml

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: "游불"

jobs:
  sync-files:
    name: "游불 translations"
    runs-on: ubuntu-22.04

    steps:

      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gettext tree
          version: 1.0

      - name: "Update"
        run: |
          # Get AM version
          AMVERSION=$(head -n 3 < APP-MANAGER | tail -n 1 | cut -d'"' -f2)
          # Files for string extraction
          list="APP-MANAGER modules/database.am modules/install.am modules/management.am modules/sandboxes.am modules/template.am"
          # Remove old pot and create po dir
          if [ -f source.pot ]; then
            rm source.pot
          fi

          for file in ${list}; do
            echo "$file"
            # Extract strings for translation
            bash --dump-po-strings "$file" >> source.pot
          done

          LANGUAGE="English"
          PACKAGE_NAME="am"
          PACKAGE_VERSION="$AMVERSION"
          TRANSLATOR_NAME="John Doe"
          TRANSLATOR_EMAIL="john.doe@example.com"
          touch temp.po
          cat <<-HEREDOC >> temp.po
          # File with translation for AM
          # FIRST AUTHOR <EMAIL@ADDRESS>, $(date +"%Y")
          msgid ""
          msgstr ""
          Project-Id-Version: ${PACKAGE_NAME} ${PACKAGE_VERSION}
          Report-Msgid-Bugs-To: https://github.com/ivan-hc/AM
          POT-Creation-Date: $(date +"%Y-%m-%d")
          PO-Revision-Date: $(date +"%Y-%m-%d")
          Last-Translator: ${TRANSLATOR_NAME} <${TRANSLATOR_EMAIL}>
          Language-Team: ${LANGUAGE} <LL@li.org>
          MIME-Version: 1.0
          Content-Type: text/plain; charset=UTF-8
          Content-Transfer-Encoding: 8bit
          Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;
          HEREDOC

          # add strings to empty file with header
          cat source.pot >> temp.po
          # remove duplicities from po file
          msguniq temp.po -o source.po || cat temp.po
          # recreate fixed pot file
          msgcat --output-file=source.pot --unique --indent --no-wrap source.po

      - name: Regen
        run: |
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          rm -f temp.p*
          git add source.po
          git add source.pot
          echo '----------------------------------------------------------------------------'

      - name: Push
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "游불 translations"
            git push && echo "translations ${{ github.run_number }} prepared" >> $GITHUB_STEP_SUMMARY
          fi
