name: "游불"

on:
  push:
    paths:
      - modules/**
      - APP-MANAGER
      # Trigger if action file change !! DEBUG important
      - .github/workflows/to-weblate.yml

  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: "游불"

jobs:
  sync-files:
    name: 游불 translations
    runs-on: ubuntu-22.04

    steps:

      - name: "Checkout source repository"
        uses: actions/checkout@v4

      - name: "Cache dependencies"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wget curl torsocks zsync gettext tree
          version: 1.0

      - name: 游불
        run: |
          sudo systemctl enable tor.service || systemctl enable tor.service
          sudo systemctl restart tor.service && wait || systemctl restart tor.service && wait
          chmod +x ./INSTALL
          sudo ./INSTALL 2> /dev/null || ./INSTALL

      # We need include translation files
      - name: "Get translations etc from outside"
        run: |
          cd /tmp/
          # Clone repo with localization
          git clone https://github.com/${{ github.repository_owner }}/monorepo monorepo
          cd monorepo
          # Copy source and translated files
          cp localization/source.po localization/source.pot /opt/am/
          # Copy translated modules
          cp -r am/modules /opt/am/
          # Copy am
          cp am/APP-MANAGER /opt/am/
          # Just for sure
          chmod a+x /opt/am/APP-MANAGER

      - name: Regen
        run: |
          # Switch to dev branch
          am --devmode-enable
          am -u
          am --translate
          rm -f /opt/am/localization/*.po~
          cp -r /opt/am/localization $GITHUB_WORKSPACE/
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          rm -f temp.p*
          git add *.po
          git add source.po
          git add source.pot
          echo '----------------------------------------------------------------------------'

      - name: Push
        run: |
          git config --global user.name "web-flow"
          git config --global user.email "noreply@github.com"
          echo '----------------------------------------------------------------------------'
          git status
          echo '----------------------------------------------------------------------------'
          if git diff-index --quiet HEAD; then
            echo "No changes to commit." >> $GITHUB_STEP_SUMMARY
          else
            git commit -m "游불"
            git push && echo "translation source prepared" >> $GITHUB_STEP_SUMMARY
          fi
