name: Check environment variables from installation scripts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: build
      if: always()
      run: |
        sudo apt-get -y update 2> /dev/null || apt-get -y update
        sudo apt-get -y install wget curl torsocks zsync 2> /dev/null || apt-get -y install git wget curl torsocks zsync
        chmod a+x ./amcheck.sh
        ./amcheck.sh
